### ISSUE TITLE
See if IDL code still runs, in any sense

### ISSUE THREAD

**Issue by davidwhogg** [moustakas/archetypes#3]
@moustakas does it?

**Comment by moustakas** [comment]
Well, the lp_\* code you wrote is project agnostic, but the build_primus_\* code I wrote has many dependencies, so, no, not really.

**Comment by moustakas** [comment]
@davidwhogg Any chance you can translate the 'lp_format_*' IDL scripts into a single python module? By later this evening I should have the binary chi^2 matrix  (for a set of emission-line galaxy continuum spectra---without the emission lines) that lp_format.pro expects, and we can spend Friday morning trying to plug this into CPLEX together.  

If not, no big deal  -- we can just run the IDL code as an intermediate step.

**Comment by davidwhogg** [comment]
Open a new issue for me to do this translation, and point to the code in the issue.

**Comment by moustakas** [comment]
Core (lp_*.pro) pieces of code run (have been tested) and the PRIMUS-specific code is on its way to being translated to project-agnostic python code, so closing this issue for now.
