### ISSUE TITLE
installing CPLEX SUX

### ISSUE THREAD

**Issue by davidwhogg** [moustakas/archetypes#9]
I finally got CPLEX installed on my computer.  That HURT.

Did @moustakas  manually add things to his path and his Python path?  If so, what?  Or did he use sym links?  Or what?

**Comment by moustakas** [comment]
I'll work on a step-by-step set of instructions, but all I did was:

```
cd ~/Applications/IBM/ILOG/CPLEX_Studio1261/cplex/python/2.7/x86-64_osx/
python setup.py install
```

**Comment by davidwhogg** [comment]
OMG you are awesome.
